### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by geek-APTX4869** [Wu0409/HSC_WSSS#1]
当eval.py中predict_dir为exps\crf\crf_8_7时，报错index 21 is out of bounds for axis 0 with size 21，可能是跟crf处理后的伪标签 生成时的键有关，如何解决呢？

**Comment by Wu0409** [comment]
你好，新年快乐 :)

使用 CRF 的 CAM 的验证代码 eval.py 需要在Line 33-34 进行以下的修改：
```python
for key in predict_dict.keys():
    tensor[key] = predict_dict[key]  # 将key+1修改为key即可
```

感谢您发现的这个问题，我会在后续markdown中更新

**Comment by geek-APTX4869** [comment]
新问题是论文中提到'∗ means the pseudo-labels are adopted the seeds with CRF without any refnement networks'，在代码中，我没有发现表1的’+CRF'列和加*的结果有什么不同？

**Comment by Wu0409** [comment]
"Mask"一列指的是最终训练分割模型的pseudo-labels，"+CRF"指的是仅仅CAM+CRF得到的结果。

通常的做法需要训练refinement网络进行后处理（例如：[PSA](https://github.com/jiwoon-ahn/psa)），但我们早期实验的时候发现在伪标签质量足够好的情况下，后处理对模型的性能不会有太大的提升（反而还会增加大量的计算成本，训练refinement网络是多阶段中最久的一步），所以我们在这篇工作中移除了这一步。"+CRF"和"Mask"在我们的工作里就是指的同一个没有训练refinement网络进行后处理的结果。

**Comment by geek-APTX4869** [comment]
如何评估使用了SEAM生成的初始seed呢，想学习一下

**Comment by Wu0409** [comment]
你好 :) 

评估SEAM生成的初始seed的方式和本工作的评估方式是一致的。整体的pipline都是先推理CAM以后，基于验证集选一个最优阈值，然后生成的伪标签与GT去计算mIoU，可以参考repo中的[eval.py](https://github.com/Wu0409/HSC_WSSS/blob/main/eval.py)。

---
The evaluation method of the initial seed generated by SEAM is consistent with the evaluation method of this work. The overall pipeline is to first infer the CAM, select an optimal threshold based on the validation set, and then calculate the mIoU with the generated pseudo labels and GT. You can refer to [eval.py](https://github.com/Wu0409/HSC_WSSS/blob/main/eval.py) in the repo.
